[theme]
base="dark"
primaryColor="#4B8B0A"
backgroundColor="#1E1E1E"
secondaryBackgroundColor="#262730"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
enableCORS = false

[client]
showSidebarNavigation = false